### ISSUE TITLE
Release 0.7.4

### ISSUE THREAD

**Issue by pedrorgirardi** [DEX-Company/starfish-clj#27]
Could we please release **v0.7.4**? I'm currently getting an exception when using `starfish.core/invoke-result` and **starfish-java v0.7.8** fixes this particular issue.

```
No result map in job id bd42c7c5b1a320fdeb9c19ff2e143931cddd72d4086bfb2001af2c4cafa91c5a result: {"results":{"time":"\"Mon Nov 04 14:52:17 ICT 2019\""},"status":"succeeded"}
```

**Comment by pedrorgirardi** [comment]
@shark8me can we do a release? My Clojars username is **pedrorgirardi-dex**.

**Comment by shark8me** [comment]
I've added you as an admin member on Clojars, you should be able to publish release now.

**Comment by pedrorgirardi** [comment]
Thanks @shark8me !
